### ISSUE TITLE
I dont know what to do first 

### ISSUE THREAD

**Issue by aplwkejrht** [ntrang086/image_captioning#2]
Sorry, cause I am poor about programming.. so i want you to teach me about the process of 
doing this well.. 
As i see.. 1. download the dataset and api 
               2. running the code using zupiter notebook
               3. input image to code 
Is it right?  
But actually i dont know the process of writting the code .. threre are too many codes you uploded ..
Is there full code that i can use?

**Comment by ntrang086** [comment]
Hi there, you need to run one notebook after another. The code can be put into 1 single notebook or script but it’s easier to follow via different notebook. I’d recommend signing up for the relevant program with Udacity so that you can grasp the fundamental concepts.
